#!/bin/sh

set -ex

SRC_DIR=${SRC_DIR:-'/tmp/src/'}

echo "Building with uploaded src from $SRC_DIR"

echo "Assemblying"

if [ "$(ls ${SRC_DIR}/*-runner | wc -l)" -eq "1" ]; then
  app_path=$(ls ${SRC_DIR}/*-runner)
  mv -v ${app_path} ${QUARKUS_HOME}/application
  chmod +x ${QUARKUS_HOME}/application
else
  >&2 echo "Could not locate a native image. Have you build a native image using mvn -Pnative before?"
  exit 1
fi

chmod +rx ${QUARKUS_HOME}
chmod +x ${QUARKUS_HOME}/application